import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen`}
        style={{ margin: 0, paddingBottom: "64px" }} // Reserve space for tab bar
      >
        <main className="max-w-md mx-auto">{children}</main>
        {/* Mobile Tab Bar */}
        <nav
          className="fixed bottom-0 left-0 w-full max-w-md mx-auto flex justify-between items-center bg-gray-100 border-t border-gray-300 h-16 px-4"
          style={{
            zIndex: 50,
            boxShadow: "0 -1px 8px rgba(0,0,0,0.05)",
          }}
        >
          <Tab icon="💬" label="Avatar" href="/avatar" />
          <Tab icon="🧠" label="Memory" href="/memory" />
          <Tab icon="🔍" label="Explore" href="/explore" />
          <Tab icon="👤" label="Profile" href="/profile" />
        </nav>
      </body>
    </html>
  );
}

// Simple Tab component
function Tab({
  icon,
  label,
  href,
}: {
  icon: string;
  label: string;
  href: string;
}) {
  return (
    <a
      href={href}
      className="flex flex-col items-center justify-center text-xs text-gray-700 hover:text-blue-600 flex-1"
      style={{ textDecoration: "none" }}
    >
      <span style={{ fontSize: "1.5rem" }}>{icon}</span>
      {label}
    </a>
  );
}
