version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      # Mount models directory for persistence
      - ./backend/notebook:/app/notebook
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    # Memory and resource limits for t3.xlarge (16GB total)
    deploy:
      resources:
        limits:
          memory: 12G  # Leave 4GB for system
        reservations:
          memory: 8G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 120s  # Increased for model loading

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    profiles:
      - production
